### ISSUE TITLE
Publish to DITA-OT plug-in registry

### ISSUE THREAD

**Issue by infotexture** [oxygenxml/dita-json#1]
Just heard Radu's presentation on this and other plug-ins from oXygen at [DITA-OT Day](https://www.oxygenxml.com/events/2019/dita-ot_day.html), and it looks like it would be very useful to the community. 👍 

Please consider submitting this to the DITA-OT plug-in registry at https://www.dita-ot.org/plugins  
 — _and possibly other oXygen plug-ins_?

For an overview of the process, see [Publishing plug-ins to the registry](https://www.dita-ot.org/dev/topics/plugins-registry.html#plugin-registry__publishing-to-registry) in the DITA-OT documentation.

🙇

**Comment by raducoravu** [comment]
Added this pull request: https://github.com/dita-ot/registry/pull/70
