### ISSUE TITLE
"Content is not allowed in prolog" in Author View of oXygen XML Editor

### ISSUE THREAD

**Issue by ClemenceRx** [oxygenxml/dita-json#2]
Hi,
I am using the dita-json plugin in oXygen XML Editor version 21.1, build 2019120214

**Issue:**
When I open the topic containing the conkeyref in Author mode (WYSIWYM mode) in oXygen XML Editor, I expect to see the content fetched from the JSON file but instead I have the following message: 'Content is not allowed in prolog.'

**Steps:**

I have succesfully integrated the dita-json plugin in the oXygen XML Editor built-in DITA-OT 3.x.

I have referred to the JSON file  in the ditamap file as follows:
`<keydef href="../../../xxx-ui/src/yyy/zzz/en.json" format="json" keys="xxx-ui"/>`

I have added a conkeyref in a topic, in order to reuse the content of the JSON file in my topic (aaa.bbb.ccc corresponds the ID in the JSON file) as follows:
`<ph conkeyref="xxx-ui/aaa.bbb.ccc"/>`

I have succesfully built an output that correclty displays the content of the JSON file which was quite surprising, because I thought there was an error.

Regards,
Clemence

**Comment by raducoravu** [comment]
@ClemenceRx the plugin is only for the publishing part, so I'm glad publishing works for you. 
Oxygen's Author visual editing mode does not use the same functionality to resolve content references to content from JSON files. Maybe in time if there will be more interest in this we'll add an improvement also on the editing side of things.
